# Generated by Django 5.1.4 on 2025-01-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Account_Transaction',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(),
        ),
    ]
